effect/src/index.ts, effect/src/prelude/definition/Effect.ts, effect/src/prelude/definition/Maybe.ts, effect/src/prelude/operations/access.ts, effect/src/prelude/operations/bind.ts, effect/src/prelude/operations/do.ts, effect/src/prelude/operations/failWith.ts, effect/src/prelude/operations/flatMap.ts, effect/src/prelude/operations/map.ts, effect/src/prelude/operations/orElse.ts, effect/src/prelude/operations/run.ts, effect/src/prelude/operations/succeedWith.ts, effect/src/prelude/operations/unit.ts, effect/src/prelude/operations/zip.ts, effect/src/utils/LazyArgument.ts, effect/tsconfig.json, src/compiler/checker.ts, src/compiler/commandLineParser.ts, src/compiler/program.ts, src/compiler/transformers/tsplus.ts, src/compiler/tsconfig.json, src/compiler/types.ts, src/compiler/utilities.ts, src/lib/es5.d.ts, src/services/goToDefinition.ts, src/services/services.ts, src/services/signatureHelp.ts
Closes #11 
This PR re-brands all instances of `ets` to `tsplus`. It also includes the fix from #13, but I figured I would put that PR up separately, just in case
=> chore: rename `ets` to `tsplus`

effect/src/index.ts, effect/src/tailrec.ts, src/compiler/checker.ts, src/compiler/diagnosticMessages.json, src/compiler/program.ts, src/compiler/transformers/tailRec.ts, src/compiler/tsconfig.json, src/compiler/types.ts, src/services/services.ts, src/services/signatureHelp.ts
Note: There may still be instances of the `A | LazyArgument<A>` union in help text, but this should get rid of a lot of them. I think we can deal with the rest in a follow-up PR.
=> Implement `@tsplus tailrec` + improve language service features

effect/src/index.ts, effect/src/prelude/definition/Maybe.ts, effect/src/prelude/operations/succeedWith.ts, effect/src/type-driven-overloads.ts, effect/src/type-driven-overloads/T.ts, effect/src/type-driven-overloads/op1.ts, effect/src/type-driven-overloads/op2.ts, src/compiler/checker.ts, src/compiler/transformers/tsplus.ts, src/compiler/types.ts, src/services/goToDefinition.ts, src/services/services.ts, src/services/signatureHelp.ts
Closes #18 
In addition to adding the type-driven overloads feature, this PR also refactors and clarifies how extensions are collected, as well as fixes a few minor bugs DX bugs:
- Resolved type parameters didn't show on `__tsplusTrace` functions
- Signature help showing `__tsplusTrace`
=> feat: type-driven fluent overload resolution ("multi-methods")

src/compiler/checker.ts
Since static variable extensions are now lazily resolved, the unresolved statics must be resolved when getting all of the extensions for a type.
Also, clears the unresolved cache on `initTsPlusTypeChecker`
=> fix: resolve static extensions when `getExtensions` is called

effect/src/prelude/operations/pipeable.ts, effect/src/prelude/pipeable/pipeable.ts, src/compiler/transformers/tsplus.ts
This PR improved the transformer to emit `Pipeable`, with #44 the emitted code looked like:
```
export var chain = (f, __tsplusTrace) => (self) => chain_(self, f, __tsplusTrace);
```
That is because the whole statement node was rebuilt instead of preserving the original statement and patching the initializer, additionally this PR removes the reverse-engineering of signatureToDeclaration and just uses the value declaration of the symbol correspondent to the argument of `Pipeable`, it doesn't carry through type information given that the transformer only runs in the js emit context and the `.d.ts` is already properly generated by TS
=> chore: improve pipeable transformer

src/compiler/checker.ts
`companion` extensions would not work across module boundaries, because `checkPropertyAccessForExtension` would get the local symbol of the class identifier (usually an import), rather than the symbol of the type.
=> fix: get type symbol instead of local identifier symbol

effect/src/class.ts, src/compiler/transformers/tsplus.ts
This bug was produced with the following steps:
- a class was annotated with a `companion` extension
- a `__call` extension was assigned to the companion
- another class extended the original class
- the subclass's constructor called `super`
- the `super` call was transformed into the `__call` extenion
=> fix: avoid transforming `super` call as `__call`

effect/src/macros.ts, src/compiler/checker.ts, src/compiler/diagnosticMessages.json, src/compiler/transformers/tsplus.ts
The `identity` macro is transformed to replace the function call with the first and only argument to the function.
The `remove` macro is transformed to replace the function call with a `void 0` statement.
=> feat(macro): add identity and remove macros

src/compiler/checker.ts, src/compiler/transformers/tsplus.ts, src/compiler/types.ts, src/services/goToDefinition.ts, src/services/signatureHelp.ts
Closes #61 
This PR makes the resolution of fluent extensions lazy. Definitions are collected on init, and are resolved as needed by the checker. Also, I simplified the resolution of lazy static extensions. Instead of calling a separate function (`getUnresolvedStaticExtension`), and then resolving manually, the whole process is done in one shot when calling `getStaticValueExtension` or `getStaticFunctionExtension`.
Making the collection of fluent extensions lazy was done to resolve an issue that sometimes occurred when the type of a fluent extension depended on the type of another extension. If the extension that was depended on was not yet collected, a `property does not exist on type ...` error was reported.
Bugfixes:
- Pipeable fluent `goToDefinition`
- …
=> Lazy fluent caching (and other various bugs)

src/compiler/checker.ts
The fully lazy resolution of fluent extensions was causing some to not be resolved properly before they were needed. This PR changes `initTsPlusChecker` to resolve fluent extensions after they are all collected. This ends up with a good compromise between lazy and eager resolution.
=> fix: resolve fluent extensions a bit more eagerly

effect/packages/package1/src/static-fluent-name-duplication.ts, src/compiler/transformers/tsplus.ts
Fixes a bug where, given a static and fluent extension on the same type with the same name, it was possible for the transformer to try to transform a static call as fluent.
=> fix(transformer): don't transform as fluent if the signature is not fluent

src/compiler/checker.ts
closes #72 
This bug was caused when one of the constituent functions of a generated pipeable function had no type parameters. `createFunctionDeclaration`/`createFunctionExpression` would be given an empty array of type parameters, when it should be given `undefined`.
=> fix: don't crash if a pipeable has no type parameters

effect/packages/package1/src/primitives.ts, src/compiler/checker.ts, src/compiler/types.ts, src/services/services.ts
This PR adds support for extensions on the following primitive types:
- `String`
- `Number`
- `Boolean`
- `BigInt`
- `Function`
- `Object`
In addition, it adds a very simple form of inheriting/overriding extensions, such that if a type that extends a primitive type (e.g. `FunctionN`) defines its own extension that overrides an extension on a primitive (e.g. `flow`), the extension from the non-primitive will be chosen.
=> feat: add support for primitive extensions

effect/packages/package1/src/union-inheritance.ts, src/compiler/checker.ts
This PR adds union inheritance collection functionality to `collectRelevantSymbols`.
=> fix: add union inheritance

Gulpfile.js, pack.sh, scripts/configurePrerelease.ts, src/compiler/program.ts
This PR changes the release string from `ets` to `tsplus`, as well as allows the use of nightly features (e.g. `moduleResolution: "Node12"`
=> chore: use tsplus in release string; allow nightly features

src/compiler/checker.ts, src/compiler/types.ts, src/services/services.ts
=> fix: `goToDefinition` for fluent extension expressions

effect/packages/package1/src/index.ts, effect/packages/package1/src/prelude/operations/bind.ts, src/compiler/checker.ts
Hopefully it isn't too intensive on the checker, closes https://github.com/ts-plus/typescript/issues/63
=> chore: restrict fluent extensions to assignable targets

effect/packages/package1/src/import-bug/1.ts, effect/packages/package1/src/import-bug/2.ts, src/compiler/checker.ts
This PR fixes an issue where imports that were used in a fluent or getter expression would be erased. See the demo case for an example.
=> fix: mark fluent and getter left nodes as referenced

effect/packages/package1/src/scope-name-conflict.ts, src/compiler/transformers/tsplus.ts
This PR covers the simplest implementation for solving #62: just create a uniquely-named declaration for each extension, and use than name when referring to the extension if the reference is in the same file in which the extension is declared.
=> fix: give local extensions unique names

src/compiler/checker.ts
Taking all the types for each declaration of a symbol ends up including unrelated tags, for example in Hash getting the declarations of the symbol Hash will return both the Hash interface and the Hash term defined via const, the Hash term has type HashOps
=> Revert inheritance changes

src/compiler/checker.ts
Fixed this bug:
#93 
>Taking all the types for each declaration of a symbol ends up including unrelated tags, for example in Hash getting the declarations of the symbol Hash will return both the Hash interface and the Hash term defined via const, the Hash term has type HashOps
=> fix: don't inherit from identically named symbol

src/compiler/checker.ts
Fixes an issue where imports were not removed when using companion call extensions.
=> fix: check companion call extension when marking alias as referenced

effect/packages/package1/src/primitives.ts, src/compiler/checker.ts
Fixes an issue where primitive type names would not be displayed correctly when hovering.
=> fix: use type flags to get primitive type name

src/compiler/checker.ts
Adds support for extensions on tuple types:
```ts
declare global {
/**
* @tsplus type ReadonlyArray
*/
interface ReadonlyArray<T> {}
/**
* @tsplus type Array
*/
interface Array<T> {}
}
function f(x: [string, number]) {
x. // <-- extensions on Array are accessible
}
function f(x: readonly [string, number]) {
x. // <-- extensions on ReadonlyArray are accessible
}
```
=> chore: use array extensions for tuple types

src/compiler/parser.ts
For TS+ any file is a module as TS+ may freely add imports to every file
=> chore: consider all project files as modules

src/compiler/parser.ts
There is a hidden tsconfig flag named `moduleDetection` when this is set to `force` every file is a module which is the condition we need for auto-imports
=> chore: revert in favour of moduleDetection flag

effect/packages/package1/src/type-and-static-repro/1.ts, src/compiler/checker.ts
Fixes statics that are named the same as their declared type, if that type is also annotated as `@tsplus type`.
For example, this didn't used to work:
```ts
/**
* @tsplus type type-and-static/A
*/
export interface A {}
/**
* @tsplus type type-and-static/AOps
*/
export interface AOps {}
export const A: AOps = {}
/**
* @tsplus type type-and-static/AAspects
*/
export interface AAspects {}
/**
* @tsplus static type-and-static/AOps $
*/
export const AAspects: AAspects = {}
// ^ Circular reference error would be here
A.$ // <-- Would cause an error
```
=> fix: set static symbol declared type to original declared type

effect/packages/package1/src/no-inherit.ts, src/compiler/checker.ts, src/compiler/diagnosticMessages.json, src/compiler/factory/nodeFactory.ts, src/compiler/parser.ts, src/compiler/types.ts
The `@tsplus no-inherit` pragma allows the user to exclude certain type tags from a type's inheritance tree.
=> feat: add no-inherit pragma
