src/compiler/checker.ts
=> Return correct LazyArgument type in `getTypeOfParameter`

effect/src/index.ts, effect/src/prelude/definition/Maybe.ts, src/compiler/checker.ts
=> Allow fluent type predicates

effect/src/index.ts, src/compiler/checker.ts, src/compiler/diagnosticMessages.json
=> chore: disallow values of type any in lazyfunction arguments

src/compiler/checker.ts
I noticed that if a return statement in a `tailRec` function was a ternary expression, it caused `tsserver` to throw. This was caused by one case of the `checkTailRecReturnStatement` node visitor not returning a node.
=> fix(tailrec): fix undefined node in node visitor

effect/src/index.ts, src/compiler/checker.ts, src/compiler/types.ts, src/services/goToDefinition.ts, src/services/services.ts
=> feat: add operator goToDefinition + instantiated quickInfo

effect/src/companion-test.ts, effect/src/companion.ts, effect/src/index.ts, src/compiler/checker.ts
Fixed companion extensions not having completions and extensions on instance type not working correctly
=> fix: completions on companion and regressions on class instance

effect/packages/package1/src/inheritance.ts, src/compiler/checker.ts
=> feat: implement extension inheritance

src/compiler/checker.ts
TypeScript considers Array types to be tuple types, according to `isTupleLikeType`, so I changed the check to explicitly check for a rest parameter.
=> fix: explicit rest parameter check

effect/packages/package1/src/prelude/operations/orElse.ts, src/compiler/checker.ts, src/services/services.ts
Closes https://github.com/ts-plus/typescript/issues/69
=> chore: support declaring operators with variable statements

effect/packages/package1/src/scope-name-conflict.ts, src/compiler/transformers/module/module.ts, src/compiler/transformers/tsplus.ts, src/compiler/transformers/utilities.ts
Transform declaration names to be unique, export the original names
=> fix: transform definition to unique name

effect/packages/package1/src/prelude/definition/List.ts, effect/packages/package1/src/type-driven-overloads.ts, effect/packages/package1/src/type-driven-overloads/op1.ts, src/compiler/checker.ts, src/compiler/diagnosticMessages.json, src/compiler/transformers/tsplus.ts, src/compiler/types.ts, src/services/goToDefinition.ts, src/services/services.ts
=> feat: ordered multi-methods

effect/packages/package1/src/non-exported-diagnostics.ts, src/compiler/checker.ts, src/compiler/diagnosticMessages.json
=> feat: add unexported extension diagnostic

effect/packages/package1/src/prelude/definition/Maybe.ts, src/services/services.ts
Closes #108 
Love when an issue can be solved by deleting code 😌
=> fix: don't add duplicate jsdoc from pipeable declarations

effect/packages/package2/src/globals2.ts, src/compiler/transformers/tsplus.ts
=> fix: remove global imports from the import map if transformed

src/compiler/checker.ts
In the following example the extensions for `Kind` were not loaded, the getTypeOrConstraint ends up being unknown
```ts
export declare namespace HKT {
const F: unique symbol;
type F = typeof F;
const R: unique symbol;
type R = typeof R;
const E: unique symbol;
type E = typeof E;
const A: unique symbol;
type A = typeof A;
const T: unique symbol;
type T = typeof T;
type _R<X extends HKT> = X extends { [R]?: (_: infer R) => void; } ? R : never;
type _E<X extends HKT> = X extends { [E]?: () => infer E; } ? E : never;
type _A<X extends HKT> = X extends { [A]?: () => infer A; } ? A : never;
}
/**
* @tsplus type Kind
*/
export type Kind<F extends HKT, R, E, A> = (F & {
[HKT.F]?: F;
[HKT.R]?: (_: R) => void;
[HKT.E]?: () => E;
[HKT.A]?: () => A;
}) extends { [HKT.T]?: infer X; } ? X : {
[HKT.F]?: …
```
=> chore: revert lazy to union and extend collect relevant symbols

src/compiler/checker.ts, src/compiler/transformers/tsplus.ts, src/compiler/transformers/tsplusDeclaration.ts, src/compiler/types.ts
Adds tags to `NodeLinks` after collection
=> perf: cache tag collection

effect/packages/package2/src/union-inheritance-repro/Equals.ts, effect/packages/package2/src/union-inheritance-repro/exit-repro.ts, src/compiler/checker.ts, src/compiler/transformers/tsplus.ts
=> fix: unannotated union inheritance

effect/packages/package2/src/derivation/auto.ts, src/compiler/checker.ts, src/compiler/diagnosticMessages.json, src/compiler/parser.ts, src/compiler/transformers/tsplus.ts, src/compiler/types.ts
=> feat: auto derivation

src/services/goToDefinition.ts
=> fix: go to correct definition of operator lhs

src/compiler/checker.ts, src/compiler/diagnosticMessages.json
=> fix: add diagnostic for `never` type in LazyArgument

src/compiler/checker.ts, src/compiler/types.ts, src/services/goToDefinition.ts, src/services/services.ts
=> fix: incorrect getter goToDefinition and hover

src/compiler/checker.ts, src/compiler/factory/utilities.ts, src/compiler/transformers/tsplus.ts, src/compiler/types.ts
=> feat: support traced getters

src/compiler/sys.ts
Based on https://github.com/microsoft/TypeScript/pull/49027
=> chore: turn on debugging in replay.io

src/compiler/transformers/tsplus.ts
=> chore: keys should be always escaped

effect/packages/package2/src/derivation/auto.ts, effect/packages/package2/src/derivation/block-scoped.ts, effect/packages/package2/src/derivation/guard.ts, effect/packages/package2/src/derivation/show.ts, effect/packages/package2/src/derivation/types.ts, src/compiler/checker.ts, src/compiler/diagnosticMessages.json, src/compiler/parser.ts, src/compiler/types.ts, testing/package.json, testing/packages/demo/package.json, testing/packages/demo/src/bug-constant.ts, testing/packages/demo/src/do-bind.ts, testing/packages/demo/src/global.ts
This PR enables derivation by type assignability, it treats interfaces nominally *when needed* to keep the algorithm for lookup reasonable.
=> Improved Derivation

effect/packages/package1/src/prelude/pipeable/pipeable-index.ts, effect/packages/package1/src/type-driven-overloads.ts, src/compiler/checker.ts, src/compiler/factory/nodeFactory.ts, src/compiler/parser.ts, src/compiler/transformers/tsplus.ts, src/compiler/types.ts
=> feat: pipeable index

effect/packages/package1/tsconfig.json, src/compiler/checker.ts, src/compiler/commandLineParser.ts, src/compiler/transformers/tsplus.ts, src/compiler/transformers/tsplusDeclaration.ts, src/compiler/types.ts
=> feat: add tsconfig option to disable tsplus

src/compiler/transformers/tailRec.ts
=> fix: transform base case return args

.npmignore, src/compiler/commandLineParser.ts, src/compiler/program.ts, src/compiler/types.ts, src/server/protocol.ts
=> feat: allow custom transformers

src/compiler/parser.ts
Separates tsconfig json paths from per-package paths.
=> fix: cache tsplus paths per package name
